set_property SRC_FILE_INFO {cfile:C:/workspace/2020/vivado-project/puf_soc/puf_soc.srcs/constrs_1/new/z_master.xdc rfile:../../../puf_soc.srcs/constrs_1/new/z_master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[0].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[0].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[1].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[1].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[2].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[2].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[3].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[3].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[4].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[4].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[5].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[5].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[6].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[6].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[7].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[7].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[8].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[8].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[9].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[9].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[10].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[10].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[11].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[11].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[12].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[12].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[13].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[13].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[14].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[14].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[15].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[15].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[16].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[16].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[17].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[17].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[18].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[18].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[19].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[19].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[20].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[20].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[21].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[21].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[22].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[22].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[23].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[23].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[24].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[24].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[25].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[25].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[26].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[26].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[27].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[27].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[28].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[28].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[29].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[29].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[30].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[30].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[31].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[31].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[32].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[32].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[33].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[33].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[34].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[34].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[35].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[35].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[36].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[36].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[37].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[37].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[38].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[38].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[39].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[39].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[40].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[40].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[41].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[41].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[42].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[42].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[43].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[43].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[44].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[44].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[45].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[45].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[46].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[46].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[47].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[47].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[48].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[48].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[49].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[49].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[50].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[50].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[51].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[51].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[52].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[52].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[53].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[53].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[54].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[54].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[55].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[55].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[56].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[56].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[57].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[57].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[58].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[58].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[59].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[59].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[60].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[60].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[61].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[61].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[62].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[62].ro2/NAND0/c}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[63].ro1/NAND0/c}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/ro_puf_0/inst/ro_blocks[63].ro2/NAND0/c}]
